version: "3"

services:
  pokedex_prod:
    container_name: pokedex-production
    image: pokedex-production
    env_file:
      - ./.env
    restart: always
networks:
  default:
    name: caddy_net
    external: true
